module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/D2W52jAfL4iBeSnEfQzSLZ?mode=ems_copy_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/SDBYFyDh/9272.jpg',
    NEWSLETTER_JID: '120363420907749813@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'HELA X MD',
    OWNER_NAME: 'Cyber Froly & Jester Exe',
    OWNER_NUMBER: '9474 3491027',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʜᴇʟᴀ-x-ᴍᴅᵀᴹ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbB61RR2phHLeBfkXq3q,
};
